# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle bootJar
      - store_artifacts:
          path: ~/repo/build/libs
          destination: build

  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle test
      - store_artifacts:
          path: ~/repo/build/reports/tests
          destination: test

  docu:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle javadoc
      - store_artifacts:
          path: ~/repo/build/docs
          destination: docs

  docker:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    steps:
      - checkout
      - run: docker login docker.nicosystems.de -u nb -p d5S2f8UVUin3D9mydxvbJQBAxi2Vr5x9AY8zXwx83F
      - run: docker build -t docker.nicosystems.de/ci-cd-demo:$CIRCLE_TAG .
      - run: docker push docker.nicosystems.de/ci-cd-demo:$CIRCLE_TAG

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
      - docu
      - docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
