# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle build

  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle test
      - store_artifacts:
          path: ~/repo/build/reports/tests
          destination: test

  docu:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: gradle javadoc
      - store_artifacts:
          path: ~/repo/build/docs
          destination: docs

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
      - docu
